version: "3"
services:
  frontend:
    build: ./src/frontend
    expose:
      - 3000
    ports:
      - 3000:3000
    env_file:
      - ./app.env
    volumes:
      - ./src/frontend:/home/frontend
    links:
      - backend
  backend:
    build: ./src/backend
    expose:
      - 80
    ports:
      - 80:80
    env_file:
      - ./app.env
    volumes:
      - ./src/backend:/home/backend
